[package]
name = "osgui"
description = "OSGUI is a component driven GUI library that is like OSUI"
license = "Apache-2.0"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "osgui"

[dependencies]
minifb = "0.28.0"
once_cell = "1.21.3"
rusttype = "0.9.3"

